plugins {
id 'com.android.application'
}

android {
namespace "duress.keyboard"
compileSdk 34

lint {
checkReleaseBuilds false
}

defaultConfig {  
    applicationId "duress.keyboard"  
    minSdk 29
    targetSdk 33
    versionCode 70
    versionName "7.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
    }  
}

}

dependencies {
}
