plugins {
id 'com.android.application'
}

android {
namespace "duress.keyboard"
compileSdk 34

buildFeatures {
    buildConfig true
}

lint {
checkReleaseBuilds false
}

defaultConfig {  
    applicationId "duress.keyboard"  
    minSdk 29
    targetSdk 33
    versionCode 71
    versionName "7.1"  
    manifestPlaceholders = [versionCode: versionCode]
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
    }  
}

}

dependencies {
}
